if("undefined"===typeof jQuery)throw Error("Bootstrap's JavaScript requires jQuery");
+function(b){b.fn.emulateTransitionEnd=function(d){var g=!1,a=this;b(this).one(b.support.transition.end,function(){g=!0});setTimeout(function(){g||b(a).trigger(b.support.transition.end)},d);return this};b(function(){var d=b.support,g;a:{g=document.createElement("bootstrap");var a={WebkitTransition:"webkitTransitionEnd",MozTransition:"transitionend",OTransition:"oTransitionEnd otransitionend",transition:"transitionend"},c;for(c in a)if(void 0!==g.style[c]){g={end:a[c]};break a}g=!1}d.transition=g})}(jQuery);
+function(b){var d=function(a){b(a).on("click",'[data-dismiss="alert"]',this.close)};d.prototype.close=function(a){function c(){d.trigger("closed.bs.alert").remove()}var e=b(this),f=e.attr("data-target");f||(f=(f=e.attr("href"))&&f.replace(/.*(?=#[^\s]*$)/,""));var d=b(f);a&&a.preventDefault();d.length||(d=e.hasClass("alert")?e:e.parent());d.trigger(a=b.Event("close.bs.alert"));a.isDefaultPrevented()||(d.removeClass("in"),b.support.transition&&d.hasClass("fade")?d.one(b.support.transition.end,c).emulateTransitionEnd(150):
c())};var g=b.fn.alert;b.fn.alert=function(a){return this.each(function(){var c=b(this),e=c.data("bs.alert");e||c.data("bs.alert",e=new d(this));"string"==typeof a&&e[a].call(c)})};b.fn.alert.Constructor=d;b.fn.alert.noConflict=function(){b.fn.alert=g;return this};b(document).on("click.bs.alert.data-api",'[data-dismiss="alert"]',d.prototype.close)}(jQuery);
+function(b){var d=function(a,c){this.$element=b(a);this.options=b.extend({},d.DEFAULTS,c);this.isLoading=!1};d.DEFAULTS={loadingText:"loading..."};d.prototype.setState=function(a){var c=this.$element,e=c.is("input")?"val":"html",f=c.data();a+="Text";f.resetText||c.data("resetText",c[e]());c[e](f[a]||this.options[a]);setTimeout(b.proxy(function(){"loadingText"==a?(this.isLoading=!0,c.addClass("disabled").attr("disabled","disabled")):this.isLoading&&(this.isLoading=!1,c.removeClass("disabled").removeAttr("disabled"))},
this),0)};d.prototype.toggle=function(){var a=!0,b=this.$element.closest('[data-toggle="buttons"]');if(b.length){var e=this.$element.find("input");"radio"==e.prop("type")&&(e.prop("checked")&&this.$element.hasClass("active")?a=!1:b.find(".active").removeClass("active"));a&&e.prop("checked",!this.$element.hasClass("active")).trigger("change")}a&&this.$element.toggleClass("active")};var g=b.fn.button;b.fn.button=function(a){return this.each(function(){var c=b(this),e=c.data("bs.button"),f="object"==
typeof a&&a;e||c.data("bs.button",e=new d(this,f));"toggle"==a?e.toggle():a&&e.setState(a)})};b.fn.button.Constructor=d;b.fn.button.noConflict=function(){b.fn.button=g;return this};b(document).on("click.bs.button.data-api","[data-toggle^=button]",function(a){var c=b(a.target);c.hasClass("btn")||(c=c.closest(".btn"));c.button("toggle");a.preventDefault()})}(jQuery);
+function(b){var d=function(a,c){this.$element=b(a);this.$indicators=this.$element.find(".carousel-indicators");this.options=c;this.paused=this.sliding=this.interval=this.$active=this.$items=null;"hover"==this.options.pause&&this.$element.on("mouseenter",b.proxy(this.pause,this)).on("mouseleave",b.proxy(this.cycle,this))};d.DEFAULTS={interval:5E3,pause:"hover",wrap:!0};d.prototype.cycle=function(a){a||(this.paused=!1);this.interval&&clearInterval(this.interval);this.options.interval&&!this.paused&&
(this.interval=setInterval(b.proxy(this.next,this),this.options.interval));return this};d.prototype.getActiveIndex=function(){this.$active=this.$element.find(".item.active");this.$items=this.$active.parent().children();return this.$items.index(this.$active)};d.prototype.to=function(a){var c=this,e=this.getActiveIndex();if(!(a>this.$items.length-1||0>a))return this.sliding?this.$element.one("slid.bs.carousel",function(){c.to(a)}):e==a?this.pause().cycle():this.slide(a>e?"next":"prev",b(this.$items[a]))};
d.prototype.pause=function(a){a||(this.paused=!0);this.$element.find(".next, .prev").length&&b.support.transition&&(this.$element.trigger(b.support.transition.end),this.cycle(!0));this.interval=clearInterval(this.interval);return this};d.prototype.next=function(){if(!this.sliding)return this.slide("next")};d.prototype.prev=function(){if(!this.sliding)return this.slide("prev")};d.prototype.slide=function(a,c){var e=this.$element.find(".item.active"),f=c||e[a](),d=this.interval,h="next"==a?"left":"right",
g="next"==a?"first":"last",k=this;if(!f.length){if(!this.options.wrap)return;f=this.$element.find(".item")[g]()}if(f.hasClass("active"))return this.sliding=!1;g=b.Event("slide.bs.carousel",{relatedTarget:f[0],direction:h});this.$element.trigger(g);if(!g.isDefaultPrevented())return this.sliding=!0,d&&this.pause(),this.$indicators.length&&(this.$indicators.find(".active").removeClass("active"),this.$element.one("slid.bs.carousel",function(){var a=b(k.$indicators.children()[k.getActiveIndex()]);a&&a.addClass("active")})),
b.support.transition&&this.$element.hasClass("slide")?(f.addClass(a),f[0].offsetWidth,e.addClass(h),f.addClass(h),e.one(b.support.transition.end,function(){f.removeClass([a,h].join(" ")).addClass("active");e.removeClass(["active",h].join(" "));k.sliding=!1;setTimeout(function(){k.$element.trigger("slid.bs.carousel")},0)}).emulateTransitionEnd(1E3*e.css("transition-duration").slice(0,-1))):(e.removeClass("active"),f.addClass("active"),this.sliding=!1,this.$element.trigger("slid.bs.carousel")),d&&this.cycle(),
this};var g=b.fn.carousel;b.fn.carousel=function(a){return this.each(function(){var c=b(this),e=c.data("bs.carousel"),f=b.extend({},d.DEFAULTS,c.data(),"object"==typeof a&&a),l="string"==typeof a?a:f.slide;e||c.data("bs.carousel",e=new d(this,f));if("number"==typeof a)e.to(a);else if(l)e[l]();else f.interval&&e.pause().cycle()})};b.fn.carousel.Constructor=d;b.fn.carousel.noConflict=function(){b.fn.carousel=g;return this};b(document).on("click.bs.carousel.data-api","[data-slide], [data-slide-to]",
function(a){var c=b(this),e,f=b(c.attr("data-target")||(e=c.attr("href"))&&e.replace(/.*(?=#[^\s]+$)/,""));e=b.extend({},f.data(),c.data());var d=c.attr("data-slide-to");d&&(e.interval=!1);f.carousel(e);(d=c.attr("data-slide-to"))&&f.data("bs.carousel").to(d);a.preventDefault()});b(window).on("load",function(){b('[data-ride="carousel"]').each(function(){var a=b(this);a.carousel(a.data())})})}(jQuery);
+function(b){var d=function(a,c){this.$element=b(a);this.options=b.extend({},d.DEFAULTS,c);this.transitioning=null;this.options.parent&&(this.$parent=b(this.options.parent));this.options.toggle&&this.toggle()};d.DEFAULTS={toggle:!0};d.prototype.dimension=function(){return this.$element.hasClass("width")?"width":"height"};d.prototype.show=function(){if(!this.transitioning&&!this.$element.hasClass("in")){var a=b.Event("show.bs.collapse");this.$element.trigger(a);if(!a.isDefaultPrevented()){if((a=this.$parent&&
this.$parent.find("> .panel > .in"))&&a.length){var c=a.data("bs.collapse");if(c&&c.transitioning)return;a.collapse("hide");c||a.data("bs.collapse",null)}var e=this.dimension();this.$element.removeClass("collapse").addClass("collapsing")[e](0);this.transitioning=1;a=function(){this.$element.removeClass("collapsing").addClass("collapse in")[e]("auto");this.transitioning=0;this.$element.trigger("shown.bs.collapse")};if(!b.support.transition)return a.call(this);c=b.camelCase(["scroll",e].join("-"));
this.$element.one(b.support.transition.end,b.proxy(a,this)).emulateTransitionEnd(350)[e](this.$element[0][c])}}};d.prototype.hide=function(){if(!this.transitioning&&this.$element.hasClass("in")){var a=b.Event("hide.bs.collapse");this.$element.trigger(a);if(!a.isDefaultPrevented()){a=this.dimension();this.$element[a](this.$element[a]())[0].offsetHeight;this.$element.addClass("collapsing").removeClass("collapse").removeClass("in");this.transitioning=1;var c=function(){this.transitioning=0;this.$element.trigger("hidden.bs.collapse").removeClass("collapsing").addClass("collapse")};
if(!b.support.transition)return c.call(this);this.$element[a](0).one(b.support.transition.end,b.proxy(c,this)).emulateTransitionEnd(350)}}};d.prototype.toggle=function(){this[this.$element.hasClass("in")?"hide":"show"]()};var g=b.fn.collapse;b.fn.collapse=function(a){return this.each(function(){var c=b(this),e=c.data("bs.collapse"),f=b.extend({},d.DEFAULTS,c.data(),"object"==typeof a&&a);!e&&f.toggle&&"show"==a&&(a=!a);e||c.data("bs.collapse",e=new d(this,f));if("string"==typeof a)e[a]()})};b.fn.collapse.Constructor=
d;b.fn.collapse.noConflict=function(){b.fn.collapse=g;return this};b(document).on("click.bs.collapse.data-api","[data-toggle=collapse]",function(a){var c=b(this),e;a=c.attr("data-target")||a.preventDefault()||(e=c.attr("href"))&&e.replace(/.*(?=#[^\s]+$)/,"");e=b(a);var f=(a=e.data("bs.collapse"))?"toggle":c.data(),d=c.attr("data-parent"),h=d&&b(d);a&&a.transitioning||(h&&h.find('[data-toggle=collapse][data-parent="'+d+'"]').not(c).addClass("collapsed"),c[e.hasClass("in")?"addClass":"removeClass"]("collapsed"));
e.collapse(f)})}(jQuery);
+function(b){function d(a){b(".dropdown-backdrop").remove();b("[data-toggle=dropdown]").each(function(){var c=g(b(this)),d={relatedTarget:this};c.hasClass("open")&&(c.trigger(a=b.Event("hide.bs.dropdown",d)),a.isDefaultPrevented()||c.removeClass("open").trigger("hidden.bs.dropdown",d))})}function g(a){var c=a.attr("data-target");c||(c=(c=a.attr("href"))&&/#[A-Za-z]/.test(c)&&c.replace(/.*(?=#[^\s]*$)/,""));return(c=c&&b(c))&&c.length?c:a.parent()}var a=function(a){b(a).on("click.bs.dropdown",this.toggle)};
a.prototype.toggle=function(a){var c=b(this);if(!c.is(".disabled, :disabled")){var l=g(c);a=l.hasClass("open");d();if(!a){if("ontouchstart"in document.documentElement&&!l.closest(".navbar-nav").length)b('<div class="dropdown-backdrop"/>').insertAfter(b(this)).on("click",d);var h={relatedTarget:this};l.trigger(a=b.Event("show.bs.dropdown",h));if(a.isDefaultPrevented())return;l.toggleClass("open").trigger("shown.bs.dropdown",h);c.focus()}return!1}};a.prototype.keydown=function(a){if(/(38|40|27)/.test(a.keyCode)){var c=
b(this);a.preventDefault();a.stopPropagation();if(!c.is(".disabled, :disabled")){var d=g(c),h=d.hasClass("open");if(!h||h&&27==a.keyCode)return 27==a.which&&d.find("[data-toggle=dropdown]").focus(),c.click();c=d.find("[role=menu] li:not(.divider):visible a, [role=listbox] li:not(.divider):visible a");c.length&&(d=c.index(c.filter(":focus")),38==a.keyCode&&0<d&&d--,40==a.keyCode&&d<c.length-1&&d++,~d||(d=0),c.eq(d).focus())}}};var c=b.fn.dropdown;b.fn.dropdown=function(c){return this.each(function(){var d=
b(this),l=d.data("bs.dropdown");l||d.data("bs.dropdown",l=new a(this));"string"==typeof c&&l[c].call(d)})};b.fn.dropdown.Constructor=a;b.fn.dropdown.noConflict=function(){b.fn.dropdown=c;return this};b(document).on("click.bs.dropdown.data-api",d).on("click.bs.dropdown.data-api",".dropdown form",function(a){a.stopPropagation()}).on("click.bs.dropdown.data-api","[data-toggle=dropdown]",a.prototype.toggle).on("keydown.bs.dropdown.data-api","[data-toggle=dropdown], [role=menu], [role=listbox]",a.prototype.keydown)}(jQuery);
+function(b){var d=function(a,c){this.options=c;this.$element=b(a);this.$backdrop=this.isShown=null;this.options.remote&&this.$element.find(".modal-content").load(this.options.remote,b.proxy(function(){this.$element.trigger("loaded.bs.modal")},this))};d.DEFAULTS={backdrop:!0,keyboard:!0,show:!0};d.prototype.toggle=function(a){return this[this.isShown?"hide":"show"](a)};d.prototype.show=function(a){var c=this,e=b.Event("show.bs.modal",{relatedTarget:a});this.$element.trigger(e);this.isShown||e.isDefaultPrevented()||
(this.isShown=!0,this.escape(),this.$element.on("click.dismiss.bs.modal",'[data-dismiss="modal"]',b.proxy(this.hide,this)),this.backdrop(function(){var e=b.support.transition&&c.$element.hasClass("fade");c.$element.parent().length||c.$element.appendTo(document.body);c.$element.show().scrollTop(0);e&&c.$element[0].offsetWidth;c.$element.addClass("in").attr("aria-hidden",!1);c.enforceFocus();var d=b.Event("shown.bs.modal",{relatedTarget:a});e?c.$element.find(".modal-dialog").one(b.support.transition.end,
function(){c.$element.focus().trigger(d)}).emulateTransitionEnd(300):c.$element.focus().trigger(d)}))};d.prototype.hide=function(a){a&&a.preventDefault();a=b.Event("hide.bs.modal");this.$element.trigger(a);this.isShown&&!a.isDefaultPrevented()&&(this.isShown=!1,this.escape(),b(document).off("focusin.bs.modal"),this.$element.removeClass("in").attr("aria-hidden",!0).off("click.dismiss.bs.modal"),b.support.transition&&this.$element.hasClass("fade")?this.$element.one(b.support.transition.end,b.proxy(this.hideModal,
this)).emulateTransitionEnd(300):this.hideModal())};d.prototype.enforceFocus=function(){b(document).off("focusin.bs.modal").on("focusin.bs.modal",b.proxy(function(a){this.$element[0]===a.target||this.$element.has(a.target).length||this.$element.focus()},this))};d.prototype.escape=function(){if(this.isShown&&this.options.keyboard)this.$element.on("keyup.dismiss.bs.modal",b.proxy(function(a){27==a.which&&this.hide()},this));else this.isShown||this.$element.off("keyup.dismiss.bs.modal")};d.prototype.hideModal=
function(){var a=this;this.$element.hide();this.backdrop(function(){a.removeBackdrop();a.$element.trigger("hidden.bs.modal")})};d.prototype.removeBackdrop=function(){this.$backdrop&&this.$backdrop.remove();this.$backdrop=null};d.prototype.backdrop=function(a){var c=this.$element.hasClass("fade")?"fade":"";if(this.isShown&&this.options.backdrop){var e=b.support.transition&&c;this.$backdrop=b('<div class="modal-backdrop '+c+'" />').appendTo(document.body);this.$element.on("click.dismiss.bs.modal",b.proxy(function(a){a.target===
a.currentTarget&&("static"==this.options.backdrop?this.$element[0].focus.call(this.$element[0]):this.hide.call(this))},this));e&&this.$backdrop[0].offsetWidth;this.$backdrop.addClass("in");a&&(e?this.$backdrop.one(b.support.transition.end,a).emulateTransitionEnd(150):a())}else!this.isShown&&this.$backdrop?(this.$backdrop.removeClass("in"),b.support.transition&&this.$element.hasClass("fade")?this.$backdrop.one(b.support.transition.end,a).emulateTransitionEnd(150):a()):a&&a()};var g=b.fn.modal;b.fn.modal=
function(a,c){return this.each(function(){var e=b(this),f=e.data("bs.modal"),l=b.extend({},d.DEFAULTS,e.data(),"object"==typeof a&&a);f||e.data("bs.modal",f=new d(this,l));if("string"==typeof a)f[a](c);else l.show&&f.show(c)})};b.fn.modal.Constructor=d;b.fn.modal.noConflict=function(){b.fn.modal=g;return this};b(document).on("click.bs.modal.data-api",'[data-toggle="modal"]',function(a){var c=b(this),e=c.attr("href"),d=b(c.attr("data-target")||e&&e.replace(/.*(?=#[^\s]+$)/,"")),e=d.data("bs.modal")?
"toggle":b.extend({remote:!/#/.test(e)&&e},d.data(),c.data());c.is("a")&&a.preventDefault();d.modal(e,this).one("hide",function(){c.is(":visible")&&c.focus()})});b(document).on("show.bs.modal",".modal",function(){b(document.body).addClass("modal-open")}).on("hidden.bs.modal",".modal",function(){b(document.body).removeClass("modal-open")})}(jQuery);
+function(b){var d=function(a,c){this.type=this.options=this.enabled=this.timeout=this.hoverState=this.$element=null;this.init("tooltip",a,c)};d.DEFAULTS={animation:!0,placement:"top",selector:!1,template:'<div class="tooltip"><div class="tooltip-arrow"></div><div class="tooltip-inner"></div></div>',trigger:"hover focus",title:"",delay:0,html:!1,container:!1};d.prototype.init=function(a,c,e){this.enabled=!0;this.type=a;this.$element=b(c);this.options=this.getOptions(e);a=this.options.trigger.split(" ");
for(c=a.length;c--;)if(e=a[c],"click"==e)this.$element.on("click."+this.type,this.options.selector,b.proxy(this.toggle,this));else if("manual"!=e){var d="hover"==e?"mouseleave":"focusout";this.$element.on(("hover"==e?"mouseenter":"focusin")+"."+this.type,this.options.selector,b.proxy(this.enter,this));this.$element.on(d+"."+this.type,this.options.selector,b.proxy(this.leave,this))}this.options.selector?this._options=b.extend({},this.options,{trigger:"manual",selector:""}):this.fixTitle()};d.prototype.getDefaults=
function(){return d.DEFAULTS};d.prototype.getOptions=function(a){a=b.extend({},this.getDefaults(),this.$element.data(),a);a.delay&&"number"==typeof a.delay&&(a.delay={show:a.delay,hide:a.delay});return a};d.prototype.getDelegateOptions=function(){var a={},c=this.getDefaults();this._options&&b.each(this._options,function(b,d){c[b]!=d&&(a[b]=d)});return a};d.prototype.enter=function(a){var c=a instanceof this.constructor?a:b(a.currentTarget)[this.type](this.getDelegateOptions()).data("bs."+this.type);
clearTimeout(c.timeout);c.hoverState="in";if(!c.options.delay||!c.options.delay.show)return c.show();c.timeout=setTimeout(function(){"in"==c.hoverState&&c.show()},c.options.delay.show)};d.prototype.leave=function(a){var c=a instanceof this.constructor?a:b(a.currentTarget)[this.type](this.getDelegateOptions()).data("bs."+this.type);clearTimeout(c.timeout);c.hoverState="out";if(!c.options.delay||!c.options.delay.hide)return c.hide();c.timeout=setTimeout(function(){"out"==c.hoverState&&c.hide()},c.options.delay.hide)};
d.prototype.show=function(){var a=b.Event("show.bs."+this.type);if(this.hasContent()&&this.enabled&&(this.$element.trigger(a),!a.isDefaultPrevented())){var c=this,a=this.tip();this.setContent();this.options.animation&&a.addClass("fade");var e="function"==typeof this.options.placement?this.options.placement.call(this,a[0],this.$element[0]):this.options.placement,d=/\s?auto?\s?/i,l=d.test(e);l&&(e=e.replace(d,"")||"top");a.detach().css({top:0,left:0,display:"block"}).addClass(e);this.options.container?
a.appendTo(this.options.container):a.insertAfter(this.$element);var d=this.getPosition(),h=a[0].offsetWidth,g=a[0].offsetHeight;if(l){var k=this.$element.parent(),l=e,n=document.documentElement.scrollTop||document.body.scrollTop,p="body"==this.options.container?window.innerWidth:k.outerWidth(),q="body"==this.options.container?window.innerHeight:k.outerHeight(),k="body"==this.options.container?0:k.offset().left,e="bottom"==e&&d.top+d.height+g-n>q?"top":"top"==e&&0>d.top-n-g?"bottom":"right"==e&&d.right+
h>p?"left":"left"==e&&d.left-h<k?"right":e;a.removeClass(l).addClass(e)}d=this.getCalculatedOffset(e,d,h,g);this.applyPlacement(d,e);this.hoverState=null;e=function(){c.$element.trigger("shown.bs."+c.type)};b.support.transition&&this.$tip.hasClass("fade")?a.one(b.support.transition.end,e).emulateTransitionEnd(150):e()}};d.prototype.applyPlacement=function(a,c){var d,f=this.tip(),g=f[0].offsetWidth,h=f[0].offsetHeight,m=parseInt(f.css("margin-top"),10),k=parseInt(f.css("margin-left"),10);isNaN(m)&&
(m=0);isNaN(k)&&(k=0);a.top+=m;a.left+=k;b.offset.setOffset(f[0],b.extend({using:function(a){f.css({top:Math.round(a.top),left:Math.round(a.left)})}},a),0);f.addClass("in");m=f[0].offsetWidth;k=f[0].offsetHeight;"top"==c&&k!=h&&(d=!0,a.top=a.top+h-k);/bottom|top/.test(c)?(h=0,0>a.left&&(h=-2*a.left,a.left=0,f.offset(a),m=f[0].offsetWidth,k=f[0].offsetHeight),this.replaceArrow(h-g+m,m,"left")):this.replaceArrow(k-h,k,"top");d&&f.offset(a)};d.prototype.replaceArrow=function(a,c,b){this.arrow().css(b,
a?50*(1-a/c)+"%":"")};d.prototype.setContent=function(){var a=this.tip(),c=this.getTitle();a.find(".tooltip-inner")[this.options.html?"html":"text"](c);a.removeClass("fade in top bottom left right")};d.prototype.hide=function(){function a(){"in"!=c.hoverState&&d.detach();c.$element.trigger("hidden.bs."+c.type)}var c=this,d=this.tip(),f=b.Event("hide.bs."+this.type);this.$element.trigger(f);if(!f.isDefaultPrevented())return d.removeClass("in"),b.support.transition&&this.$tip.hasClass("fade")?d.one(b.support.transition.end,
a).emulateTransitionEnd(150):a(),this.hoverState=null,this};d.prototype.fixTitle=function(){var a=this.$element;(a.attr("title")||"string"!=typeof a.attr("data-original-title"))&&a.attr("data-original-title",a.attr("title")||"").attr("title","")};d.prototype.hasContent=function(){return this.getTitle()};d.prototype.getPosition=function(){var a=this.$element[0];return b.extend({},"function"==typeof a.getBoundingClientRect?a.getBoundingClientRect():{width:a.offsetWidth,height:a.offsetHeight},this.$element.offset())};
d.prototype.getCalculatedOffset=function(a,c,b,d){return"bottom"==a?{top:c.top+c.height,left:c.left+c.width/2-b/2}:"top"==a?{top:c.top-d,left:c.left+c.width/2-b/2}:"left"==a?{top:c.top+c.height/2-d/2,left:c.left-b}:{top:c.top+c.height/2-d/2,left:c.left+c.width}};d.prototype.getTitle=function(){var a=this.$element,b=this.options;return a.attr("data-original-title")||("function"==typeof b.title?b.title.call(a[0]):b.title)};d.prototype.tip=function(){return this.$tip=this.$tip||b(this.options.template)};
d.prototype.arrow=function(){return this.$arrow=this.$arrow||this.tip().find(".tooltip-arrow")};d.prototype.validate=function(){this.$element[0].parentNode||(this.hide(),this.options=this.$element=null)};d.prototype.enable=function(){this.enabled=!0};d.prototype.disable=function(){this.enabled=!1};d.prototype.toggleEnabled=function(){this.enabled=!this.enabled};d.prototype.toggle=function(a){a=a?b(a.currentTarget)[this.type](this.getDelegateOptions()).data("bs."+this.type):this;a.tip().hasClass("in")?
a.leave(a):a.enter(a)};d.prototype.destroy=function(){clearTimeout(this.timeout);this.hide().$element.off("."+this.type).removeData("bs."+this.type)};var g=b.fn.tooltip;b.fn.tooltip=function(a){return this.each(function(){var c=b(this),e=c.data("bs.tooltip"),f="object"==typeof a&&a;if(e||"destroy"!=a)if(e||c.data("bs.tooltip",e=new d(this,f)),"string"==typeof a)e[a]()})};b.fn.tooltip.Constructor=d;b.fn.tooltip.noConflict=function(){b.fn.tooltip=g;return this}}(jQuery);
+function(b){var d=function(a,b){this.init("popover",a,b)};if(!b.fn.tooltip)throw Error("Popover requires tooltip.js");d.DEFAULTS=b.extend({},b.fn.tooltip.Constructor.DEFAULTS,{placement:"right",trigger:"click",content:"",template:'<div class="popover"><div class="arrow"></div><h3 class="popover-title"></h3><div class="popover-content"></div></div>'});d.prototype=b.extend({},b.fn.tooltip.Constructor.prototype);d.prototype.constructor=d;d.prototype.getDefaults=function(){return d.DEFAULTS};d.prototype.setContent=
function(){var a=this.tip(),b=this.getTitle(),d=this.getContent();a.find(".popover-title")[this.options.html?"html":"text"](b);a.find(".popover-content")[this.options.html?"string"==typeof d?"html":"append":"text"](d);a.removeClass("fade top bottom left right in");a.find(".popover-title").html()||a.find(".popover-title").hide()};d.prototype.hasContent=function(){return this.getTitle()||this.getContent()};d.prototype.getContent=function(){var a=this.$element,b=this.options;return a.attr("data-content")||
("function"==typeof b.content?b.content.call(a[0]):b.content)};d.prototype.arrow=function(){return this.$arrow=this.$arrow||this.tip().find(".arrow")};d.prototype.tip=function(){this.$tip||(this.$tip=b(this.options.template));return this.$tip};var g=b.fn.popover;b.fn.popover=function(a){return this.each(function(){var c=b(this),e=c.data("bs.popover"),f="object"==typeof a&&a;if(e||"destroy"!=a)if(e||c.data("bs.popover",e=new d(this,f)),"string"==typeof a)e[a]()})};b.fn.popover.Constructor=d;b.fn.popover.noConflict=
function(){b.fn.popover=g;return this}}(jQuery);
+function(b){function d(a,c){var e,f=b.proxy(this.process,this);this.$element=b(a).is("body")?b(window):b(a);this.$body=b("body");this.$scrollElement=this.$element.on("scroll.bs.scroll-spy.data-api",f);this.options=b.extend({},d.DEFAULTS,c);this.selector=(this.options.target||(e=b(a).attr("href"))&&e.replace(/.*(?=#[^\s]+$)/,"")||"")+" .nav li > a";this.offsets=b([]);this.targets=b([]);this.activeTarget=null;this.refresh();this.process()}d.DEFAULTS={offset:10};d.prototype.refresh=function(){var a=
this.$element[0]==window?"offset":"position";this.offsets=b([]);this.targets=b([]);var c=this;this.$body.find(this.selector).map(function(){var d=b(this),d=d.data("target")||d.attr("href"),f=/^#./.test(d)&&b(d);return f&&f.length&&f.is(":visible")&&[[f[a]().top+(!b.isWindow(c.$scrollElement.get(0))&&c.$scrollElement.scrollTop()),d]]||null}).sort(function(a,b){return a[0]-b[0]}).each(function(){c.offsets.push(this[0]);c.targets.push(this[1])})};d.prototype.process=function(){var a=this.$scrollElement.scrollTop()+
this.options.offset,b=(this.$scrollElement[0].scrollHeight||this.$body[0].scrollHeight)-this.$scrollElement.height(),d=this.offsets,f=this.targets,g=this.activeTarget,h;if(a>=b)return g!=(h=f.last()[0])&&this.activate(h);if(g&&a<=d[0])return g!=(h=f[0])&&this.activate(h);for(h=d.length;h--;)g!=f[h]&&a>=d[h]&&(!d[h+1]||a<=d[h+1])&&this.activate(f[h])};d.prototype.activate=function(a){this.activeTarget=a;b(this.selector).parentsUntil(this.options.target,".active").removeClass("active");a=b(this.selector+
'[data-target="'+a+'"],'+this.selector+'[href="'+a+'"]').parents("li").addClass("active");a.parent(".dropdown-menu").length&&(a=a.closest("li.dropdown").addClass("active"));a.trigger("activate.bs.scrollspy")};var g=b.fn.scrollspy;b.fn.scrollspy=function(a){return this.each(function(){var c=b(this),e=c.data("bs.scrollspy"),f="object"==typeof a&&a;e||c.data("bs.scrollspy",e=new d(this,f));if("string"==typeof a)e[a]()})};b.fn.scrollspy.Constructor=d;b.fn.scrollspy.noConflict=function(){b.fn.scrollspy=
g;return this};b(window).on("load",function(){b('[data-spy="scroll"]').each(function(){var a=b(this);a.scrollspy(a.data())})})}(jQuery);
+function(b){var d=function(a){this.element=b(a)};d.prototype.show=function(){var a=this.element,c=a.closest("ul:not(.dropdown-menu)"),d=a.data("target");d||(d=(d=a.attr("href"))&&d.replace(/.*(?=#[^\s]*$)/,""));if(!a.parent("li").hasClass("active")){var f=c.find(".active:last a")[0],g=b.Event("show.bs.tab",{relatedTarget:f});a.trigger(g);g.isDefaultPrevented()||(d=b(d),this.activate(a.parent("li"),c),this.activate(d,d.parent(),function(){a.trigger({type:"shown.bs.tab",relatedTarget:f})}))}};d.prototype.activate=
function(a,c,d){function f(){g.removeClass("active").find("> .dropdown-menu > .active").removeClass("active");a.addClass("active");h?(a[0].offsetWidth,a.addClass("in")):a.removeClass("fade");a.parent(".dropdown-menu")&&a.closest("li.dropdown").addClass("active");d&&d()}var g=c.find("> .active"),h=d&&b.support.transition&&g.hasClass("fade");h?g.one(b.support.transition.end,f).emulateTransitionEnd(150):f();g.removeClass("in")};var g=b.fn.tab;b.fn.tab=function(a){return this.each(function(){var c=b(this),
e=c.data("bs.tab");e||c.data("bs.tab",e=new d(this));if("string"==typeof a)e[a]()})};b.fn.tab.Constructor=d;b.fn.tab.noConflict=function(){b.fn.tab=g;return this};b(document).on("click.bs.tab.data-api",'[data-toggle="tab"], [data-toggle="pill"]',function(a){a.preventDefault();b(this).tab("show")})}(jQuery);
+function(b){var d=function(a,c){this.options=b.extend({},d.DEFAULTS,c);this.$window=b(window).on("scroll.bs.affix.data-api",b.proxy(this.checkPosition,this)).on("click.bs.affix.data-api",b.proxy(this.checkPositionWithEventLoop,this));this.$element=b(a);this.affixed=this.unpin=this.pinnedOffset=null;this.checkPosition()};d.RESET="affix affix-top affix-bottom";d.DEFAULTS={offset:0};d.prototype.getPinnedOffset=function(){if(this.pinnedOffset)return this.pinnedOffset;this.$element.removeClass(d.RESET).addClass("affix");
var a=this.$window.scrollTop();return this.pinnedOffset=this.$element.offset().top-a};d.prototype.checkPositionWithEventLoop=function(){setTimeout(b.proxy(this.checkPosition,this),1)};d.prototype.checkPosition=function(){if(this.$element.is(":visible")){var a=b(document).height(),c=this.$window.scrollTop(),e=this.$element.offset(),f=this.options.offset,g=f.top,h=f.bottom;"top"==this.affixed&&(e.top+=c);"object"!=typeof f&&(h=g=f);"function"==typeof g&&(g=f.top(this.$element));"function"==typeof h&&
(h=f.bottom(this.$element));c=null!=this.unpin&&c+this.unpin<=e.top?!1:null!=h&&e.top+this.$element.height()>=a-h?"bottom":null!=g&&c<=g?"top":!1;this.affixed!==c&&(this.unpin&&this.$element.css("top",""),e="affix"+(c?"-"+c:""),f=b.Event(e+".bs.affix"),this.$element.trigger(f),f.isDefaultPrevented()||(this.affixed=c,this.unpin="bottom"==c?this.getPinnedOffset():null,this.$element.removeClass(d.RESET).addClass(e).trigger(b.Event(e.replace("affix","affixed"))),"bottom"==c&&this.$element.offset({top:a-
h-this.$element.height()})))}};var g=b.fn.affix;b.fn.affix=function(a){return this.each(function(){var c=b(this),e=c.data("bs.affix"),f="object"==typeof a&&a;e||c.data("bs.affix",e=new d(this,f));if("string"==typeof a)e[a]()})};b.fn.affix.Constructor=d;b.fn.affix.noConflict=function(){b.fn.affix=g;return this};b(window).on("load",function(){b('[data-spy="affix"]').each(function(){var a=b(this),c=a.data();c.offset=c.offset||{};c.offsetBottom&&(c.offset.bottom=c.offsetBottom);c.offsetTop&&(c.offset.top=
c.offsetTop);a.affix(c)})})}(jQuery);